version: 2
jobs:
  build:
    docker:
    - image: 'circleci/ruby:2.5.5'
    environment:
      BUNDLE_PATH: ~/bundle
    steps:
    - checkout
    - restore_cache:
        keys:
        - bundle-{{ checksum "Gemfile.lock" }}
        - bundle-

    - run:
        name: Install Gem Depedencies
        command: |
          bundle install
          bundle exec appraisal install

    - save_cache:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
        - ~/bundle

    - run: bundle exec appraisal rspec

